---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      chart: cilium
      version: 1.15.1
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    # cluster:
    #   name: monitorwombat
    #   id: 1
    hubble:
      enabled: true
      #   metrics:
      #     enabled:
      #     - dns:query
      #     - drop
      #     - tcp
      #     - flow
      #     - port-distribution
      #     - icmp
      #     - http
      #     serviceMonitor:
      #       enabled: false
      #     dashboards:
      #       enabled: true
      #       annotations:
      #         grafana_folder: Cilium
      relay:
        enabled: true
        rollOutPods: true
        #     prometheus:
        #       serviceMonitor:
        #         enabled: false
      ui:
        enabled: true
        rollOutPods: true
        ingress:
          enabled: true
          className: internal
          annotations:
            hajimari.io/icon: simple-icons:cilium
          hosts:
          - &host "hubble.test"
    # tls:
    # - hosts:
    #   - *host
    nodeinit:
      enabled: true
      reconfigureKubelet: true
      removeCbrBridge: true
    cni:
      binPath: /home/kubernetes/bin
    gke:
      enabled: true
    ipam:
      mode: kubernetes
    ipv4NativeRoutingCIDR: 5.0.0.0/16
    ingressController:
      enabled: true
      default: true
      service:
        type: ClusterIP
        annotations:
          cloud.google.com/neg: '{"exposed_ports": {"80":{"name": "ingressgateway"}}}'
