apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnWk5NbzNkNzQ5aWdFZ0R5
            a2duZzFWNldRNmJ2Nnc5U2lVOVRCZXYrMFJ3Ckp4UXZXbnZBRGNDQjBVZWNBZS8w
            R0VpcWFNWlZZSmpNRmF2Ri9xSnpkUTgKLS0tIFBYRDRVb3hJQjBDUDFwWXppRzRu
            L1pXc1pBSWo0VEtGRkZHVTdxeWNnS3cKozOxz7Ei0TLPutYrDLJ7XuAeWNxZQPUk
            hMyBOCeoYei1VdD0T/uwAcu+kpDlCdy6xd036h8GXGxcrgRSiyaX/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-08T14:48:20Z"
    mac: ENC[AES256_GCM,data:j1ZzuFo0tAYIrRtejizQ7ycff7wd33mVRrjZHKSrouDqoc0qZth9o6+GqfEO4MYpHP1mKFBUEwCXLm+LnGpdLTqlFoblHhoFBkDBwUWOcQMdna3IJoi4JrA3//b5PdEwnIm/5nGQS+KplR3OPv/Xdk9oZiI1o8jnYnXrkv1ocIw=,iv:K/d46VCnLpzrKe6xhceS1Zcx+uGQFXznrgCe/fNV46A=,tag:ueDa4FejHbLsoaS5DFkbVg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
