apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:/SqIgNDdlkKl9lBpWkYJvFU81RYLY4wGB1Mql5kH1jGssv3O3ebMLw==,iv:Q5Z5qFn75dgJ11XNR+Plt+q7+WFMF8hLxYbx3tVwS3Y=,tag:m6yID0ThlJNlPIx9M65W/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmcE1FSEk4cXZmaFJ5TnBI
            UXpwdWFyRlQyVGdoYTc3NW9mRENqdTl2M0QwCnZkZGg2TzJ3NnVrb0hkbWh4WjJS
            c3VVVjhsUEx2cmlUTk9DTU9jOVVKV1UKLS0tIHZXK2Nwd0Y4eHlaeCt5cUJSWEFp
            SitVUTdnb0FVY3I0SCtuQjJMVXFUVjAKb+A3iW8A6NgkUzbnzCYkzNj4PrPPQnRK
            YPbglXtEYDorBSYPeeJtNGO7WiU7zL0Pf5BdUPpXznMPtQ3oGzAqxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-15T19:30:40Z"
    mac: ENC[AES256_GCM,data:rTAMPg/S+UuSBA5ASiJLMSfLzxmRvdUHEqqCkYkZNwYnWKkbx5DAuwoGFzLMis2s/R03GupBQ7/0RPQtcB9F27DW66raE6CxC/zfP4mNX3c132Knk9kI54hi9syVhIIZ+aQCCDH43gl+AN5JVvIf0wCi5pB6yEmoB8Dx1OpwMzk=,iv:kcnaL5OxG/gtYbAgqqN4dvweTX8fiyd87UbLP0BRa3Y=,tag:LqZHRtAMHLpTEG6FkdZHwQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
