apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:pSHoCf1xSL10xoMHNNE1nZQqllUMuLaUXx4iS4bIZDY+HZ90lZWeGQ==,iv:/XrnWVimtvRDaJJG8fyw58jBKCqCzbW7WK4Gks2SVmo=,tag:WfTyGQoyI2C822KAm/foLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5M0s3OEhVbk11ZHgrQWJ3
            WVFCYTVRbmIrZ3ZhZCtlQnE3NzJnNjVEeVVrCnE1MHN3aC90UkZWMTFyTyt4ZW1w
            L1ZRMGk3MXBuV0haK1Uwemp0MzdHeEEKLS0tIC9KNWJhV0YxWG1wTlgxRVAyUk9k
            dmtTZUkyZFJCdjN4Ly9DVjc1Zy9weHMKzhrZQUO9PKyMgXVsP9jYS2CNSP17Y9kI
            vRh3awu9NeXRKSlXW4jennXXq0/N951B+5Q9xU4u2hg1hcJGuqRQcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-11T18:51:54Z"
    mac: ENC[AES256_GCM,data:VzeVEc30rqjBjBu9wJPTD8SSqjWwsFG2cwg9lTcZf7bM+4/V6wIoOKVrFr5ZpOya/RMzjahIvnPdIfycpGG1WU9xQ7RjuQFPWhAD2MyDAE7dXxSc4+xMIqAjvRy5m5O4S1dXzMz/XUNC7GLjHJHZgrGNhX9MCo6/gakhWJg/nHc=,iv:XXuc4+U6Gu0ztxwVWaG3YjhDzPv4Hkz6Z40Ns2HDe7w=,tag:IrRTstsuTx74b1l8ueN9fA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
