apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:l9zWKxrC4pxPBcQSEgZ32hGcfytyDooZtVG1osBZa58rld3JXxet6A==,iv:/SkbDtACwZpGcuWiNrKhVx7NJUNOvBavE+IlkFodka8=,tag:cwZbITth4vVMXvseMioSrg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQd21EcXZ2bHpOUHh0K3dI
            R2VLeEw2K1JicnRXdnRRK1cxVGh1Rm1TVXpBCkE0aEQ3aU1McENJc0plMHhsVmd6
            T0xTYlJjcWdoOVpPZ2RYbUZZSDJTZkEKLS0tIEROdWFYVmRUOWEwMDZVV1p3UVBz
            SWJGRTNXZUpLMmxrZ3dIdlFQT2MzMDgKkS+8SqwLbrMktwC2NMhbiRD5torKdmfw
            fRwtY6YAvsBdrfmbpjmry6E5BNrO4KgitR+Vr6ZfxyYv/R2BQPaxdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-21T16:37:54Z"
    mac: ENC[AES256_GCM,data:TVu3A52HhMdhmxDilr/TPbyCtNpBUaV26Vr17P/jkXTHikN2ibsimaQZypDEn23/Khqgn4qtja/6VwE66Tr52GCv5HCVf7guWJy87drTpDyTr8lbpt3yCuRhnZZY0OgxaTMjALMjpDcbbyhZU2eLeB44tIHX6ydQixHu2HZxPSQ=,iv:L20dfLl1r5i14050FDBB+WcviPPYUjjsSJCO4mX9E+4=,tag:oIWwEn+Xw/sZQjBTIESffg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
