apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:ShyxBixs12LCUwPCxcODpaqWXWxNIdfeHYyk3RCfaU8w5iLgCrFKQQ==,iv:GpD6KMu/lkZZSvLl01UppWs6aBC5jgPLYH9D+SUaHgI=,tag:Fn+S7LylQ4AYB/j9acqmwg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUlpYeFBPWFRqY1NMbDhF
            RGU4YUNMdG01UXE2blREemg2Q01SOFdJOUVnCnFRQjZvcnNKR01EMnZ0WmdkUDQ1
            eW8zdEMvUzVZbDAvTnVSWUVQV0pUejQKLS0tIE8vQWtFajBaVS82WmZReElqZGhT
            UCthNXZGb0I4cExYRjNEU2pjc0UrdEkKcpHjeY8kbT9Q6JbbH62gfyyxrIIxCfBD
            ZmRz3AC7lAQ4AtbzONieHqDHWD0vMhWG5CMrQaXKRosuGyzijMJAxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-20T18:34:11Z"
    mac: ENC[AES256_GCM,data:pGPLbL3+V7uhBctNmmFn8aeyA0YT7IWng6WJqz0iSzmkYL60Sv+Z2Him6EDE1KBQwB4Ix67hBhpAriqXD5geFSTGLJKvLUSidTzY4r5WobVGFQFR3xB6DoRwLamVydtVdgD3asB6wSzJB6EhSLShW0G2tXp22GJT7Al8rhlUYfE=,iv:D27pAl7n4VZM8XG45F8RjYJrOSRfD8bJEEio0ygZxPE=,tag:admmRsnSyjgcuaSf+w/uJg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
