apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:icuOCsXslvf7mXFferhhbdh0myLuq56OVFEywy4zxBy1MAOtQt4j8g==,iv:2A/9IJIcfFTfFIxgKqDpB4NBfI9pcZrt02LmY9/tA4A=,tag:J9jP68ip//1I7bkIot3b6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3OHRYRm5zbGN3ejJKbmVi
            TmNjN2RuRXZ5Z3dPMDFlQmVNYjlrcWxKVkNRClZJSFJkMGhpbUVzWFp1YmF6MFJs
            VnFBa2tEYXE4NkRwa1FZUFkvNG42WGMKLS0tIEw0YXFMaWt2Ris4aU0zSlllME9H
            YkNwbjBpb0RVNStoYklueTZXcDB1MXMK2P1tYDVvlqvbikRt3afEyiT0W4UyJWAu
            avluuA9IwMGCC6Y1jbLKEV5hanhmEAsIsKtZ6dMk8YFUUY6PoHBQEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-26T12:15:28Z"
    mac: ENC[AES256_GCM,data:wxtOikNZi18GZAEjE6XOCmj2rvJ+K/D4fPA3CIHcyLWqWQEP3hSPPlRZWjdSMhnLQxw9y8nGo/hdSz8bk4Lh6AWcg1eYTsWCjRc3jtwmQUgOCfqbcdiZCo6+hL4sAok9LaFtTjSSgD9IT9Wh2bCDFK1FAHaecz+cD+HTSrBD3cs=,iv:LN4+XnIFc58KAFTd8ngNJmhZxaio4djOGRZVQqMMvuY=,tag:SukqbPP9tpXvc0/ZQdlvMw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
