apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:vnzErpVVVtE0hUFEesh55xZKjsyVwrQL4dGIJSktqyYLg1qYr+RkVg==,iv:29YeeB2kVHq1lbHYvS3Ph26vDBd7b9T5/xZPOjcHN2M=,tag:PegqdBJy6d73dyCUWIttcA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMDRLVlZ3MkZqaGVoY25F
            Vy92bmhZWjFuMzcvaW14bVFrOFBDOHA2TlFZCnRTTmhpVW5yaGVZVlVpL1lROStM
            cHZkRk1Tc3dXaVVKZERSMTcrYTRUTDAKLS0tICszYUNxZlJLZmZwMkhmU3hmOW5p
            N0VxWVZMMi8waEVYaWRMM2JHS09YbEEKdGKCyzrdgl4wJcdXLfAsE5geEtoNJlNP
            DaW9sh/HR/fvtVG2mrLBNJj7+V+CVm+VGGqncYMlizY6NYgl7CAGAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-11T18:51:55Z"
    mac: ENC[AES256_GCM,data:5O14qZzU1g4/hqq9Ibw7BAywbStZ41kvDQHWQo/ecJT3gh9ockAWt4fUEUY9LDSL3iImCok0+qaLP3/pvmgz7orEAVafhWoAm8gZGq9VLH8g1CyXNU14Bk8oEzhdnkGItfhSy8w/ducC74o5CGuscNxUOoRYoXGMOmUNcn3sgfI=,iv:09sPh5SaY6S1YAUGWIEVNU8wCqPLd0CB/VY4xDobj5w=,tag:Kupaxq8hZVmToJcwOtT6kQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
