apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:r3b708KSLRblYQyUUMKRrK6Ztw==,iv:ZWthlc2ZQDCrJJi2JKaWECUC4EQWlxD7uvUFGxui26k=,tag:WS1pFug7u1QXLkQXSpAFJA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:W4+fFx9NJktEFrMxT4ix1w==,iv:r00pdi4HsXiCe+Gqk5nzb50iI+3AO2Blq7KPI9Sk0Ic=,tag:dE8TB++TixBB+AxUy32I1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ptththqpxnx0zuzmq0peq9x30vqgdedjsdlsuzxr5gfc36mnwqlsylrpr8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUEhWNHNEMm82R2UySHpD
            NXdsbHNWZEZVeGs5QitvS0d2SGhuT3V1TkVnCnZDNkJ5eHMzOGpzSmNSVWdGcUhC
            MnRFWTMydzdWVnVhL3JYSzlRZVZ1cGsKLS0tIFlEQzhCZDhKK0pjNzJNQzA5eGpU
            bjlrRHZOaGxSZGcwK1lKb0tKRTFabmsKuRPbLu3Py+PBamOePnCoRX4N/hMohW8k
            y1yGs2M3Ep3TGAMng9oeUo+z+RxqvWE7qm7056SCQvK5trKJaaK2gA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-04T19:02:28Z"
    mac: ENC[AES256_GCM,data:KAXKzTVc7vzPVNGJIT8+gq+JL9vVd/S9VgF59wsoETtBgUxI54dIcVoaX5sqaxmwSruJ6XSuLa4rr08qvhxONjwX+mTuTHiWBFiZPnU+fWylZzDtnKw3pch/zxT06rSHB90seXnEKqwy68CyyybZ5zjop1p7iZm//qfQR4DlJJA=,iv:kWqa5obeasc/JV8enPe3sZzTT68s5UhlL0svLkCjizw=,tag:M+6eEVdWRDTFQYFNBUOZTA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
