# cluster:
#   name: monitorwombat
#   id: 1
# hubble:
#   enabled: true

#   relay:
#     enabled: true
#     rollOutPods: true
#   ui:
#     enabled: true
#     rollOutPods: true
#     ingress:
#       enabled: true
#       className: internal
#       annotations:
#         hajimari.io/icon: simple-icons:cilium
#       hosts:
#       - &host "hubble.test"
nodeinit:
  enabled: true
  reconfigureKubelet: true
  removeCbrBridge: true
cni:
  binPath: /home/kubernetes/bin
gke:
  enabled: true
ipam:
  mode: kubernetes
ipv4NativeRoutingCIDR: 5.0.0.0/16
ingressController:
  enabled: true
  default: true
  service:
    type: ClusterIP
    annotations:
      cloud.google.com/neg: '{"exposed_ports": {"80":{"name": "ingressgateway"}}}'
